spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
      routes:
        - id : r1
          uri: http://localhost:8081/
          predicates:
              - Path= /customers/**
        - id : r2
          uri: http://localhost:8082/
          predicates:
              - Path= /products/**

